### get game info
GET http://localhost/api/v1/game-info
Accept: application/json

### change image game
PUT http://localhost/api/v1/image-game
Accept: application/json
Content-Type: application/json

{
 "gameInfo" : {
   "level" : 1,
   "questions" : 10,
   "corrects" : 0
 },
  "imageInfo" : {
    "uuid" : "",
    "pcImage" : "",
    "mobileImage" : ""
  },
  "guessInfo" : {
    "currentGuess": 0,
    "inputLetters": []
  }
}

### get level info
PUT http://localhost/api/v1/level
Accept: application/json
Content-Type: application/json

{
  "level" : 3,
  "questions": 0
}

### guess
POST http://localhost/api/v1/guess
Accept: application/json
Content-Type: application/json

{
  "gameDataEntity" : {"imageId" : "61f38e47-4e7e-11ef-857a-00155d40afad"},
  "guessInfo" :{"currentGuess": "n", "inputLetters" : []}
}
