### get game info
GET http://localhost/api/v1/game-info
Accept: application/json

### level 1
PUT http://localhost/api/v1/image-game
Accept: application/json
Content-Type: application/json

{
 "gameInfo" : {
   "level" : 1,
   "questions" : 1,
   "correct" : 9
 },
  "imageInfo" : {
    "uuid" : "",
    "pcImage" : "",
    "mobileImage" : ""
  },
  "guessInfo" : {
    "wrongLetters": ["a","b"]
  },
  "questionInfo": {
    "answer": "snoring",
    "postfix": "",
    "prefix": ""
  }
}